
common:

  solver:
    type: Solver

  seed: 2048
  cuda_deterministic: False
  fp16: True

  wandb:
    use: False
    key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    suffix_run_name: None
    entity: entity
    project: project
    resume: False
    notes: 
    wandb_log_all: True
    save_artifacts: False

  num_workers: 4
  max_iter: 50000
  gradient_acc: 1
      
  backbone:
    type: FaRLVisualFeatures
    kwargs:
      model_type: base
      model_path: <your_path>/pretrain/FaRL-Base-Patch16-LAIONFace20M-ep64.pth
      drop_path_rate: 0.2
      forced_input_resolution: 512

  heads:
    type: TaskSpecificHeadsHolder
    kwargs: 
      subnets_cfg:
        recog:
          type: RecognitionHead
          kwargs:
            task_name: recog_ms1mv3
        age:
          type: SwinFaceHead
          kwargs:
            outputs: [101]
            indices: [5, 7, 9, 11]
            task_names: ["age_morph2"]
        biattr:
          type: SwinFaceHead
          kwargs:
            outputs: [40]
            indices: [5, 7, 9, 11]
            task_names: ["biattr_celeba"]    
        affect:
          type: SwinFaceHead
          kwargs:
            outputs: [7, 7]
            indices: [5, 7, 9, 11]
            task_names: ["affect_affectnet", "affect_rafdb"]   
        parsing:
          type: MMSEG_UPerHead
          kwargs:
            outputs: [19]
            out_types: ["ParsingOutput"]
            task_names: ["parsing_celebam"]
            indices: [3, 5, 7, 11]
            out_size: [512, 512]
        align:
          type: MMSEG_UPerHead
          kwargs:
            outputs: [68]
            out_types: ["AlignOutput"]
            task_names: ["align_300w"]
            indices: [3, 5, 7, 11]
            out_size: [512, 512]

  model_entry:
      type: aio_entry
      kwargs:
        size_group:
          group_0:
            task_types: ["recog", "age", "biattr", "affect"]
            input_size: 112
          group_1:
            task_types: ["parsing","align"]
            input_size: 512

  optimizer:
    type: AdamW
    kwargs:
      weight_decay: 0.05

  backbone_multiplier: 0.1
  heads_multiplier: 1.

  lr_scheduler:
    type: 'Cosine'
    kwargs:
      eta_min: 0.
      base_lr: 1.e-5
      warmup_lr: 5.e-4
      warmup_steps: 2000
  lr_base: 512
  lr_scale: False

  print_interval: 10
  save_interval: 5000
  evaluate_interval: 2500

  task_weight:
    recog: 1.0
    age: 1.0
    biattr: 1.0
    affect: 1.0
    parsing: 1.0
    align: 1.0


# For 2 Cards.
tasks:
  0:
    name: recog_ms1mv3
    loss_weight: 128.

    dataset:
      type: MXFaceDataset
      kwargs:
        data_path:  <your_path>/data/MS1MV3/
        augmentation:
          type: recognition_mxface_transform
          kwargs:
            input_size: 112

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 128
      shuffle_strategy: 1

    loss:
      type: MarginCosineProductLoss
      kwargs:
        in_features: 512
        out_features: 93431
        scale: 64
        margin: 0.4

    evaluator:
      type: RecogEvaluator
      use: True
      kwargs: 
        mark: eval_recog
        val_targets: ['lfw', 'cfp_fp', "agedb_30", 'calfw', 'cplfw', 'mlfw', 'lfw_m']
        rec_prefix: <your_path>/data/verification/
        image_size: [112, 112]

  1:
    name: age_morph2
    loss_weight: 32.

    dataset:
      type: MORPH2Dataset_V2
      kwargs:
        data_path: <your_path>/data/MORPH2
        augmentation:
          type: attribute_train_transform
          kwargs:
            input_size: 112
        train: True

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 32
      shuffle_strategy: 1

    loss:
      type: AgeLoss_DLDLV2
      kwargs: {}

    evaluator:
      type: AgeEvaluator_V2
      use: True
      kwargs: 
        mark: eval_morph2_test
        test_batch_size: 32
        test_dataset_cfg:
          type: MORPH2Dataset_V2
          kwargs:
            data_path:  <your_path>/data/MORPH2
            augmentation:
              type: attribute_test_transform
              kwargs:
                input_size: 112
            train: False  

  2:
    name: biattr_celeba
    loss_weight: 32.

    dataset:
      type: BiAttrDataset
      kwargs:
        data_path: <your_path>/data/CelebA/
        augmentation:
          type: attribute_train_transform
          kwargs:
            input_size: 112
        dataset_name: "CelebA"
        split: "trainval"

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 32
      shuffle_strategy: 1

    loss:
      type: CEL_Sigmoid
      kwargs: {}

    evaluator:
      type: BiAttrEvaluator
      use: True
      kwargs: 
        mark: eval_celeba_test
        test_batch_size: 32
        test_dataset_cfg:
          type: BiAttrDataset
          kwargs:
            data_path:  <your_path>/data/CelebA/
            augmentation:
              type: attribute_test_transform
              kwargs:
                input_size: 112
            dataset_name: "CelebA"
            split: "test"   

  3:
    name: affect_affectnet
    loss_weight: 32.

    dataset:
      type: AffectNetDataset_V2
      kwargs:
        data_path: <your_path>/data/AffectNet/
        augmentation:
          type: attribute_train_transform
          kwargs:
            input_size: 112
        train: True

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 32
      shuffle_strategy: 1

    loss:
      type: MyCrossEntropyLoss
      kwargs: {}

    evaluator:
      type: SingferEvaluator
      use: True
      kwargs: 
        mark: eval_affect_test
        test_batch_size: 32
        test_dataset_cfg:
          type: AffectNetDataset_V2
          kwargs:
            data_path:  <your_path>/data/AffectNet/
            augmentation:
              type: attribute_test_transform
              kwargs:
                input_size: 112
            train: False 

  4:
    name: affect_rafdb
    loss_weight: 8.

    dataset:
      type: RAFDBDataset
      kwargs:
        data_path: <your_path>/data/RAF-DB/basic/
        augmentation:
          type: attribute_train_transform
          kwargs:
            input_size: 112
        train: True

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 8
      shuffle_strategy: 1

    loss:
      type: MyCrossEntropyLoss
      kwargs: {}

    evaluator:
      type: SingferEvaluator
      use: True
      kwargs: 
        mark: eval_rafdb_test
        test_batch_size: 32
        test_dataset_cfg:
          type: RAFDBDataset
          kwargs:
            data_path:  <your_path>/data/RAF-DB/basic/
            augmentation:
              type: attribute_test_transform
              kwargs:
                input_size: 112
            train: False 

  5:
    name: parsing_celebam
    loss_weight: 2.

    dataset:
      type: CelebAMaskHQDataset
      kwargs:
        data_path: <your_path>/data/CelebAMask-HQ/
        augmentation:
          type: celebam_train_transform
          kwargs:
            input_size: 512
        split: train_val

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 2
      shuffle_strategy: 1

    loss:
      type: ParsingLoss
      kwargs: {}

    evaluator:
      type: ParsingEvaluator
      use: True
      kwargs: 
        mark: eval_celebam_test
        test_batch_size: 2
        label_names: ['background', 'neck', 'face', 'cloth', 'rr', 
                      'lr', 'rb', 'lb', 're', 'le', 
                      'nose', 'imouth', 'llip', 'ulip', 'hair',
                      'glass', 'hat', 'earr', 'neckl']
        bg_label_name: background
        test_dataset_cfg:
          type: CelebAMaskHQDataset
          kwargs:
            data_path: <your_path>/data/CelebAMask-HQ/
            augmentation:
              type: celebam_test_transform
              kwargs:
                input_size: 512
                warp_factor: 0.0
            split: test
        test_post_trans:
          type: celebam_test_post_transform
          kwargs:
            input_size: 512
            warp_factor: 0.0

  6:
    name: align_300w
    loss_weight: 2.

    dataset:
      type: IBUG300WDataset
      kwargs:
        data_path: <your_path>/data/300W/
        augmentation:
          type: align_train_transform
          kwargs:
            input_size: 512
            shift_sigma: 0.05
            rot_sigma: 0.174
            scale_sigma: 0.1
            scale_mu: 0.8
            warp_factor: 0.0
        split: train

    sampler:
      type: DistributedGivenIterationSampler
      batch_size: 2
      shuffle_strategy: 1

    loss:
      type: AlignLoss
      kwargs: 
        input_size: 512
        heatmap_size: 128
        heatmap_radius: 5.0

    evaluator:
      type: IBUG300WEvaluator
      use: True
      kwargs: 
        mark: eval_300w_test
        test_batch_size: 1
        test_dataset_cfg:
          type: IBUG300WDataset
          kwargs:
            data_path: <your_path>/data/300W/
            augmentation:
              type: align_test_transform
              kwargs:
                input_size: 512
                scale_mu: 0.8
                warp_factor: 0.0
            split: valid_challenge # You can choose the following subsets: valid valid_challenge valid_common
        test_post_trans:
          type: align_test_post_transform
          kwargs:
            input_size: 512
            warp_factor: 0.0

